import {useEffect,useRef,useState} from 'react';
import {ArrowLeft,ArrowUpRight,Check,ClipboardList,RefreshCw,Save,Send} from 'lucide-react';
import {clientId,request,track,type User,type WorkItem} from '../types';

type Props={user:User|null;item:WorkItem|null;onSelect:(item:WorkItem|null)=>void;onOpen:(item:WorkItem)=>void;onLogin:()=>void;onLot:(lot:string)=>void;onAsk:()=>void;revision:number};
const kinds:Record<string,string>={quality:'품질 검토',shipment:'출하 검토',claim:'문의·클레임',general:'일반 확인'};
export function WorkBoard({user,item,onSelect,onOpen,onLogin,onLot,onAsk,revision}:Props){
 const [items,setItems]=useState<WorkItem[]>([]),[users,setUsers]=useState<User[]>([]),[filter,setFilter]=useState('all'),[search,setSearch]=useState('');
 const [note,setNote]=useState(''),[recipient,setRecipient]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(false),[notice,setNotice]=useState('');
 const [draft,setDraft]=useState(''),[draftType,setDraftType]=useState('internal');
 const lock=useRef(false),pending=useRef<{key:string;id:string}|null>(null);
 useEffect(()=>{setNote('');setRecipient('');setError('');setDraft('');setNotice('');pending.current=null},[item?.id]);
 async function load(){if(!user)return;setLoading(true);setError('');try{const [list,people]=await Promise.all([request<WorkItem[]>('/work-items'),request<User[]>('/users')]);setItems(list);setUsers(people)}catch(e){setError((e as Error).message)}finally{setLoading(false)}}
 useEffect(()=>{load()},[user?.id,revision]);
 async function refresh(){if(!item){await load();return}setError('');try{onSelect(await request<WorkItem>('/work-items/'+item.id));setNotice('최신 업무를 불러왔습니다. 작성 중인 메모는 유지했습니다.')}catch(e){setError((e as Error).message)}}
 async function change(action:string){
  if(!item||lock.current)return;lock.current=true;setBusy(true);setError('');setNotice('');
  const key=JSON.stringify([item.id,item.version,action,note,recipient]);if(pending.current?.key!==key)pending.current={key,id:clientId()};
  try{const next=await request<WorkItem>('/work-items/'+item.id,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({expected_version:item.version,request_id:pending.current.id,action,text:note,recipient_id:recipient||null})});onSelect(next);const done={handoff:'handoff_sent',acknowledge:'handoff_acknowledged',complete:'review_completed'}[action] as 'handoff_sent'|undefined;if(done)track(done,{work:item.id});setNote('');pending.current=null;setNotice('저장했습니다. '+new Date(next.updated_at).toLocaleString('ko-KR'));await load()}catch(e){setError((e as Error).message)}finally{lock.current=false;setBusy(false)}
 }
 function buildDraft(type:string){
  if(!item)return;setDraftType(type);
  setDraft(type==='customer'?`안녕하세요. 문의하신 ${item.lot_id||'제품'} 관련 안내 초안입니다.\n\n현재 관련 기록을 담당자가 확인하고 있습니다. 확인된 사항과 후속 일정을 검토한 뒤 안내드리겠습니다.\n\n[담당자가 확인된 사실과 회신 예정일을 작성해 주세요.]`:`[내부 검토 초안] ${item.title}\n대상 LOT: ${item.lot_id||'미선택'}\n업무 상태: ${item.status} (출하 승인과 별개)\n\n${item.snapshot?.answer.text||'저장된 답변 없음'}\n\n추가 확인: ${item.notes.at(-1)?.text||'담당자 작성 필요'}\n\n샘플 자료를 기반으로 작성한 초안입니다.`);
 }
 function download(){const url=URL.createObjectURL(new Blob([draft],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`${draftType==='customer'?'고객회신':'내부검토'}_초안.txt`;a.click();URL.revokeObjectURL(url)}
 if(!user)return <section className="login-empty"><ClipboardList size={36}/><h2>현장에서 확인한 일을<br/>다음 기기에서 이어보세요.</h2><p>로그인하면 LOT·답변·근거·메모를 함께 저장하고 담당자에게 인계할 수 있습니다.</p><button className="primary" onClick={onLogin}>업무 계정으로 로그인</button></section>;
 const canEdit=item&&(user.id===item.assignee_id||user.role==='admin');
 const list=items.filter(w=>(filter==='all'||filter==='mine'&&w.assignee_id===user.id||filter==='handoff'&&w.assignee_id===user.id&&w.status==='인계 대기'||filter==='done'&&w.status==='검토 완료')&&[w.title,w.lot_id,w.status].join(' ').includes(search));
 return <div className="work-board">
  <div className="work-toolbar">{item?<button onClick={()=>onSelect(null)}><ArrowLeft size={17}/>업무 목록</button>:<div className="filter-tabs">{[['all','전체 업무'],['mine','내 업무'],['handoff','받은 인계'],['done','완료']].map(([value,label])=><button className={filter===value?'selected':''} key={value} onClick={()=>setFilter(value)}>{label}</button>)}</div>}<button disabled={busy||loading} onClick={refresh}><RefreshCw size={17}/>새로고침</button></div>
  {error&&<p role="alert" className="error-note">{error}</p>}{notice&&<p role="status" className="info-note">{notice}</p>}
  {!item?<><label className="form-label">업무 검색<input placeholder="제목·LOT·상태" value={search} onChange={e=>setSearch(e.target.value)}/></label>{loading?<p role="status">업무를 불러오고 있습니다.</p>:list.length?<div className="work-list">{list.map(w=><button className="work-row" key={w.id} onClick={()=>onOpen(w)}><span className="work-kind">{kinds[w.kind]}</span><strong>{w.title}</strong><code>{w.lot_id||'LOT 미선택'}</code><span>{w.status} · {users.find(u=>u.id===w.assignee_id)?.name||'담당자'}</span><small>{new Date(w.updated_at).toLocaleString('ko-KR')}</small><ArrowUpRight size={18}/></button>)}</div>:<div className="empty"><ClipboardList/><p>저장한 업무가 없습니다. LOT를 열거나 답변에서 ‘업무로 저장’을 선택하세요.</p></div>}</>:<>
   <section className="work-detail"><span className="work-kind">{kinds[item.kind]} · {item.status}</span><h2>{item.title}</h2><p>담당 {users.find(u=>u.id===item.assignee_id)?.name||'미확인'} · 수정 {new Date(item.updated_at).toLocaleString('ko-KR')}</p><div className="answer-actions">{item.lot_id&&<button onClick={()=>onLot(item.lot_id!)}>LOT·측정 근거 열기 <ArrowUpRight size={16}/></button>}<button onClick={onAsk}>이 업무에 질문하기 <ArrowUpRight size={16}/></button></div><p className="info-note">업무 검토 상태입니다. ERP 출하 승인과 공정 상태는 변경하지 않습니다.</p></section>
   {item.handoff&&<section className="review-section"><h3>인계 요청</h3><p className="pre-wrap">{item.handoff.request}</p><small>{item.handoff.acknowledged_at?'수신 확인: '+new Date(item.handoff.acknowledged_at).toLocaleString('ko-KR'):'수신 확인 대기'}</small>{item.status==='인계 대기'&&item.handoff.recipient_id===user.id&&<button className="primary" disabled={busy} onClick={()=>change('acknowledge')}><Check size={16}/>인계 수신 확인</button>}</section>}
   {item.snapshot&&<section className="review-section"><h3>저장 당시 답변과 근거</h3>{(item.snapshots?.length??0)>1&&<details><summary>이전 답변·근거 {item.snapshots!.length-1}건</summary>{item.snapshots!.slice(0,-1).map((s,i)=><details key={i}><summary>{s.question}</summary><p className="pre-wrap">{s.answer.text}</p><pre className="snapshot">{JSON.stringify({documents:s.answer.evidence,records:s.answer.records},null,2)}</pre></details>)}</details>}<p className="pre-wrap">{item.snapshot.answer.text}</p><small>기록 기준: {item.snapshot.answer.context?.as_of} · 보존: {item.snapshot.answer.captured_at&&new Date(item.snapshot.answer.captured_at).toLocaleString('ko-KR')}</small><details><summary>보존된 근거 전체 보기</summary><pre className="snapshot">{JSON.stringify({documents:item.snapshot.answer.evidence,records:item.snapshot.answer.records},null,2)}</pre></details><p className="muted">보존된 근거입니다. 현재 기록은 LOT 상세에서 다시 확인하세요.</p></section>}
   <section className="review-section"><h3>검토 메모</h3>{item.notes.map((n,i)=><article className="work-note" key={i}><p className="pre-wrap">{n.text}</p><small>{n.author} · {new Date(n.at).toLocaleString('ko-KR')}</small></article>)}{canEdit?<><label className="form-label">확인한 사실·미확인 사항·다음 요청<textarea value={note} onChange={e=>setNote(e.target.value)} rows={4} maxLength={6000} placeholder="검토 결과와 다음 담당자가 확인할 내용을 남겨 주세요."/></label><div className="answer-actions"><button className="primary" disabled={busy||!note.trim()} onClick={()=>change('note')}><Save size={16}/>메모 저장</button>{user.role!=='operator'&&item.status!=='검토 완료'&&<button className="secondary" disabled={busy||!note.trim()||item.status==='인계 대기'} onClick={()=>change('complete')}><Check size={16}/>검토 완료</button>}{item.status==='검토 완료'&&<button className="secondary" disabled={busy} onClick={()=>change('reopen')}>재확인으로 전환</button>}</div><div className="handoff-form"><label className="form-label">인계받을 담당자<select value={recipient} onChange={e=>setRecipient(e.target.value)}><option value="">담당자 선택</option>{users.filter(u=>u.id!==user.id).map(u=><option key={u.id} value={u.id}>{u.name} · {u.role==='operator'?'생산':u.role==='reviewer'?'품질 검토':'관리'}</option>)}</select></label><p className="muted">위 메모를 인계 요청으로 저장합니다. 수신자가 확인하면 검토 대기로 바뀝니다.</p><button className="secondary" disabled={busy||!recipient||!note.trim()} onClick={()=>change('handoff')}><Send size={16}/>선택한 담당자에게 인계</button></div></>:<p className="info-note">현재 담당자가 메모와 상태를 변경할 수 있습니다.</p>}</section>
   <section className="review-section"><h3>검토·회신 초안</h3><div className="answer-actions"><button onClick={()=>buildDraft('internal')}>내부 검토 초안</button><button onClick={()=>buildDraft('customer')}>고객 회신 초안</button></div>{draft&&<><label className="form-label">{draftType==='customer'?'고객 회신 초안 · 사실과 일정을 확인하세요':'내부 검토용 · 외부 전달 전 확인하세요'}<textarea rows={8} value={draft} onChange={e=>setDraft(e.target.value)}/></label><button className="secondary" onClick={download}>편집한 초안 내려받기</button><p className="muted">현재 화면에서 편집한 초안입니다. 내려받아 보관하세요. 외부로 발송하지 않습니다.</p></>}</section>
   <details className="review-section"><summary>업무 이력 {item.events.length}건</summary>{item.events.map((event,i)=><p key={i}>{event.action} · {event.actor} · {new Date(event.at).toLocaleString('ko-KR')}</p>)}</details>
  </>}
 </div>;
}
